# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WajmjKr8xz9tKagBfmW2mHg02DJSV0zP
"""

import streamlit as st
import torch
from torchvision import transforms
from PIL import Image
import torch.nn as nn
from torchvision import models

# تحميل الموديل
@st.cache_resource
def load_model():
    model = models.resnet18(pretrained=False)
    num_ftrs = model.fc.in_features
    model.fc = nn.Linear(num_ftrs, 2)
    model.load_state_dict(torch.load("xray_model.pth", map_location="cpu"))
    model.eval()
    return model

model = load_model()

# تهيئة تحويل الصورة
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor()
])

# عنوان الواجهة
st.title("🩺 تطبيق تحليل صور الأشعة بالذكاء الاصطناعي")

# رفع الصورة
uploaded_file = st.file_uploader("حمّل صورة الأشعة (X-Ray)", type=["jpg", "png", "jpeg"])

if uploaded_file is not None:
    image = Image.open(uploaded_file).convert("RGB")
    st.image(image, caption="صورة الأشعة", use_container_width=True)

    if st.button("تحليل الصورة"):
        img_tensor = transform(image).unsqueeze(0)
        with torch.no_grad():
            outputs = model(img_tensor)
            _, predicted = torch.max(outputs, 1)

        if predicted.item() == 0:
            st.success("✅ الصورة طبيعية (لا يوجد مرض)")
        else:
            st.error("⚠️ احتمال وجود مشكلة في الأشعة")

st.markdown("---")
st.caption("📘 تطبيق تجريبي باستخدام PyTorch و Streamlit")