# -*- coding: utf-8 -*-
"""TorchScript

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WajmjKr8xz9tKagBfmW2mHg02DJSV0zP
"""

import torch
from torchvision import models
import torch.nn as nn

model = models.resnet18(pretrained=False)
num_ftrs = model.fc.in_features
model.fc = nn.Linear(num_ftrs, 2)
model.load_state_dict(torch.load("xray_model.pth", map_location="cpu"))
model.eval()

traced_model = torch.jit.trace(model, torch.rand(1, 3, 224, 224))
traced_model.save("xray_model_mobile.pt")
print("✅ تم حفظ نسخة TorchScript لاستخدامها في التطبيق")